<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3S9DULk\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3S9DULk/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3S9DULk.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\Container3S9DULk\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \Container3S9DULk\appAppKernelDevDebugContainer([
    'container.build_hash' => '3S9DULk',
    'container.build_id' => '1ccb5e31',
    'container.build_time' => 1708338478,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3S9DULk');
