<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3iFKxPwVnZEzSvMNNXPz'."\n".'yEULCbkzuSAqoaeIx1HbAaxmmUQwHckgP5moNA6NOVyWMp1EbTTo3d/CJ42ADRxp'."\n".'A91UPkkTd5gEvg8kuxmSwSZHrpGQVoG1ePaX3ZwnIfRiwv+bumqo2h8whrdqJJVb'."\n".'Mdl+ylcGVxaPiGlJ/utx/kQ2hFNJHAkhth9k3e4vj07jjPYDjR2RVPSZ2WUG/Tfg'."\n".'LIZdNceFz9UKGzhhO+Xj6GZmZ8g7EPb7pp2GbKir9Ojso8+r3Q72pUEF3CFfvDOg'."\n".'juI6TZ8XoGwCWIVYfPbeE9cjroI//qkBEVCKyAqIGF7c0xsGf1qPsmOvGumZLfXF'."\n".'5QIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
