<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX2dQ62D\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX2dQ62D/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerX2dQ62D.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerX2dQ62D\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerX2dQ62D\appAppKernelProdContainer([
    'container.build_hash' => 'X2dQ62D',
    'container.build_id' => '8c00efc5',
    'container.build_time' => 1708875791,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX2dQ62D');
