<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1I5ux4F\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1I5ux4F/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container1I5ux4F.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container1I5ux4F\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container1I5ux4F\appAppKernelProdContainer([
    'container.build_hash' => '1I5ux4F',
    'container.build_id' => 'a62158a9',
    'container.build_time' => 1707837973,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1I5ux4F');
