<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWTPudbH\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWTPudbH/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerWTPudbH.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerWTPudbH\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerWTPudbH\appAppKernelProdContainer([
    'container.build_hash' => 'WTPudbH',
    'container.build_id' => '6afe4885',
    'container.build_time' => 1706504869,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWTPudbH');
