<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLKvUVKV\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLKvUVKV/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerLKvUVKV.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerLKvUVKV\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerLKvUVKV\appAppKernelProdContainer([
    'container.build_hash' => 'LKvUVKV',
    'container.build_id' => '442ca792',
    'container.build_time' => 1706504904,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLKvUVKV');
